import type { TrackMeta, ConceptMeta } from '$lib/types/roadmap';

export const frontendTrack: TrackMeta = {
	slug: 'frontend',
	title: 'Front-End Developer',
	description: 'Build modern, accessible, performant web interfaces',
	roles: ['frontend', 'fullstack', 'freelancer', 'designer-coder'],
	layers: {
		foundation: [
			'html-semantics', 'css-box-model', 'css-flexbox', 'css-grid', 'css-responsive',
			'js-fundamentals', 'js-dom', 'js-events', 'js-async', 'js-modules'
		],
		framework: [
			'svelte-basics', 'svelte-runes', 'svelte-components', 'svelte-stores',
			'sveltekit-routing', 'sveltekit-load', 'sveltekit-forms', 'sveltekit-hooks',
			'tailwind-basics', 'tailwind-responsive'
		],
		professional: [
			'a11y-fundamentals', 'perf-optimization', 'testing-basics', 'git-workflow',
			'ci-cd', 'seo-basics', 'design-systems', 'typescript-basics'
		]
	}
};

export const frontendConcepts: ConceptMeta[] = [
	{
		slug: 'html-semantics',
		title: 'HTML Semantics',
		description: 'Meaningful HTML structure with proper elements',
		layer: 'foundation',
		order: 1,
		prerequisites: [],
		unlocks: ['css-box-model', 'a11y-fundamentals'],
		estimatedMinutes: 60,
		whyNext: 'Everything on the web starts with HTML structure',
		whatBreaksIfSkipped: 'Screen readers can\'t navigate, SEO suffers, CSS targeting breaks',
		projectProof: 'Build a blog article page using only semantic HTML',
		tags: ['html', 'semantics', 'accessibility']
	},
	{
		slug: 'css-box-model',
		title: 'CSS Box Model',
		description: 'Understanding padding, margin, border, and content areas',
		layer: 'foundation',
		order: 2,
		prerequisites: ['html-semantics'],
		unlocks: ['css-flexbox', 'css-grid'],
		estimatedMinutes: 45,
		whyNext: 'Every layout decision depends on understanding the box model',
		whatBreaksIfSkipped: 'Layouts break unpredictably, spacing inconsistencies',
		projectProof: 'Create a card component with proper spacing',
		tags: ['css', 'layout', 'box-model']
	},
	{
		slug: 'css-flexbox',
		title: 'CSS Flexbox',
		description: 'One-dimensional layout for rows and columns',
		layer: 'foundation',
		order: 3,
		prerequisites: ['css-box-model'],
		unlocks: ['css-grid', 'css-responsive'],
		estimatedMinutes: 90,
		whyNext: 'Flexbox handles 80% of common layout patterns',
		whatBreaksIfSkipped: 'Navigation bars, card layouts, centering all become painful',
		projectProof: 'Build a navigation bar and card grid using flexbox',
		tags: ['css', 'flexbox', 'layout']
	},
	{
		slug: 'css-grid',
		title: 'CSS Grid',
		description: 'Two-dimensional layout for complex page structures',
		layer: 'foundation',
		order: 4,
		prerequisites: ['css-box-model'],
		unlocks: ['css-responsive', 'tailwind-basics'],
		estimatedMinutes: 90,
		whyNext: 'Grid handles complex layouts that flexbox alone can\'t',
		whatBreaksIfSkipped: 'Dashboard layouts, magazine-style grids become over-engineered',
		projectProof: 'Build a dashboard layout with sidebar and grid content',
		tags: ['css', 'grid', 'layout']
	},
	{
		slug: 'css-responsive',
		title: 'Responsive Design',
		description: 'Media queries, fluid typography, and mobile-first approach',
		layer: 'foundation',
		order: 5,
		prerequisites: ['css-flexbox', 'css-grid'],
		unlocks: ['tailwind-responsive'],
		estimatedMinutes: 60,
		whyNext: 'Most traffic is mobile. Responsive design is non-negotiable.',
		whatBreaksIfSkipped: 'Site breaks on phones, tablets, different screen sizes',
		projectProof: 'Make your dashboard responsive from mobile to ultrawide',
		tags: ['css', 'responsive', 'mobile-first']
	},
	{
		slug: 'js-fundamentals',
		title: 'JavaScript Fundamentals',
		description: 'Variables, functions, control flow, data types, and scope',
		layer: 'foundation',
		order: 6,
		prerequisites: [],
		unlocks: ['js-dom', 'js-events', 'js-async', 'js-modules'],
		estimatedMinutes: 120,
		whyNext: 'JavaScript powers all interactivity on the web',
		whatBreaksIfSkipped: 'Can\'t write any dynamic behavior or understand frameworks',
		projectProof: 'Build a calculator with pure JavaScript logic',
		tags: ['javascript', 'fundamentals']
	},
	{
		slug: 'js-dom',
		title: 'DOM Manipulation',
		description: 'Selecting, creating, modifying, and removing DOM elements',
		layer: 'foundation',
		order: 7,
		prerequisites: ['js-fundamentals'],
		unlocks: ['js-events', 'svelte-basics'],
		estimatedMinutes: 60,
		whyNext: 'Understanding the DOM is what frameworks abstract away',
		whatBreaksIfSkipped: 'Can\'t debug why framework renders look wrong',
		projectProof: 'Build a dynamic todo list with vanilla JS',
		tags: ['javascript', 'dom']
	},
	{
		slug: 'js-events',
		title: 'Event Handling',
		description: 'Event listeners, delegation, bubbling, and custom events',
		layer: 'foundation',
		order: 8,
		prerequisites: ['js-dom'],
		unlocks: ['svelte-basics'],
		estimatedMinutes: 45,
		whyNext: 'Every user interaction triggers events',
		whatBreaksIfSkipped: 'Memory leaks, missed interactions, broken UX',
		projectProof: 'Add keyboard shortcuts and click handlers to your todo app',
		tags: ['javascript', 'events']
	},
	{
		slug: 'js-async',
		title: 'Async JavaScript',
		description: 'Promises, async/await, fetch API, and error handling',
		layer: 'foundation',
		order: 9,
		prerequisites: ['js-fundamentals'],
		unlocks: ['sveltekit-load'],
		estimatedMinutes: 90,
		whyNext: 'All data fetching and server communication is async',
		whatBreaksIfSkipped: 'API calls fail silently, race conditions, unhandled rejections',
		projectProof: 'Fetch data from a public API and display it',
		tags: ['javascript', 'async', 'promises']
	},
	{
		slug: 'js-modules',
		title: 'ES Modules',
		description: 'Import/export, named vs default, dynamic imports',
		layer: 'foundation',
		order: 10,
		prerequisites: ['js-fundamentals'],
		unlocks: ['svelte-components'],
		estimatedMinutes: 30,
		whyNext: 'Every modern framework uses ES modules for code organization',
		whatBreaksIfSkipped: 'Can\'t organize code, circular dependencies',
		projectProof: 'Refactor your calculator into separate modules',
		tags: ['javascript', 'modules', 'es6']
	},
	{
		slug: 'svelte-basics',
		title: 'Svelte Basics',
		description: 'Component structure, reactivity, and template syntax',
		layer: 'framework',
		order: 11,
		prerequisites: ['js-dom', 'js-events'],
		unlocks: ['svelte-runes', 'svelte-components'],
		estimatedMinutes: 90,
		whyNext: 'Svelte compiles your components to efficient vanilla JS',
		whatBreaksIfSkipped: 'Can\'t build interactive UIs with the framework',
		projectProof: 'Rebuild your todo app as a Svelte component',
		tags: ['svelte', 'components', 'reactivity']
	},
	{
		slug: 'svelte-runes',
		title: 'Svelte 5 Runes',
		description: '$state, $derived, $effect, $props, and $bindable',
		layer: 'framework',
		order: 12,
		prerequisites: ['svelte-basics'],
		unlocks: ['svelte-stores', 'svelte-components'],
		estimatedMinutes: 120,
		whyNext: 'Runes are the core of Svelte 5 reactivity',
		whatBreaksIfSkipped: 'Can\'t manage state properly, stale values, infinite loops',
		projectProof: 'Build a reactive form with live validation using runes',
		tags: ['svelte', 'runes', 'state']
	},
	{
		slug: 'svelte-components',
		title: 'Component Patterns',
		description: 'Props, slots/snippets, events, composition, and context',
		layer: 'framework',
		order: 13,
		prerequisites: ['svelte-basics', 'js-modules'],
		unlocks: ['sveltekit-routing'],
		estimatedMinutes: 90,
		whyNext: 'Good component design makes apps maintainable',
		whatBreaksIfSkipped: 'Spaghetti components, prop drilling, repeated code',
		projectProof: 'Build a reusable modal and dropdown component',
		tags: ['svelte', 'components', 'patterns']
	},
	{
		slug: 'svelte-stores',
		title: 'State Management',
		description: 'Context, .svelte.ts modules, and shared reactive state',
		layer: 'framework',
		order: 14,
		prerequisites: ['svelte-runes'],
		unlocks: ['sveltekit-hooks'],
		estimatedMinutes: 60,
		whyNext: 'Apps need state shared across components',
		whatBreaksIfSkipped: 'Global state is scattered, hard to debug',
		projectProof: 'Create a theme system using .svelte.ts state',
		tags: ['svelte', 'state', 'stores']
	},
	{
		slug: 'sveltekit-routing',
		title: 'SvelteKit Routing',
		description: 'File-based routing, layouts, params, and navigation',
		layer: 'framework',
		order: 15,
		prerequisites: ['svelte-components'],
		unlocks: ['sveltekit-load', 'sveltekit-forms'],
		estimatedMinutes: 60,
		whyNext: 'Routing is the skeleton of any multi-page application',
		whatBreaksIfSkipped: 'Can\'t build multi-page apps, broken navigation',
		projectProof: 'Build a blog with nested routes and dynamic slugs',
		tags: ['sveltekit', 'routing', 'navigation']
	},
	{
		slug: 'sveltekit-load',
		title: 'SvelteKit Load Functions',
		description: 'Server and universal load functions, data flow, types',
		layer: 'framework',
		order: 16,
		prerequisites: ['sveltekit-routing', 'js-async'],
		unlocks: ['sveltekit-forms', 'sveltekit-hooks'],
		estimatedMinutes: 90,
		whyNext: 'Load functions power server-side data fetching',
		whatBreaksIfSkipped: 'Waterfalls, loading flickers, SEO-invisible content',
		projectProof: 'Build a blog that loads posts from markdown files',
		tags: ['sveltekit', 'data', 'ssr']
	},
	{
		slug: 'sveltekit-forms',
		title: 'SvelteKit Form Actions',
		description: 'Form actions, progressive enhancement, validation',
		layer: 'framework',
		order: 17,
		prerequisites: ['sveltekit-routing'],
		unlocks: ['sveltekit-hooks'],
		estimatedMinutes: 60,
		whyNext: 'Forms are how users interact with your data',
		whatBreaksIfSkipped: 'No progressive enhancement, broken without JS',
		projectProof: 'Build a contact form with server-side validation',
		tags: ['sveltekit', 'forms', 'actions']
	},
	{
		slug: 'sveltekit-hooks',
		title: 'SvelteKit Hooks',
		description: 'Server hooks, handle, resolve, and middleware patterns',
		layer: 'framework',
		order: 18,
		prerequisites: ['sveltekit-load', 'svelte-stores'],
		unlocks: ['a11y-fundamentals', 'perf-optimization'],
		estimatedMinutes: 60,
		whyNext: 'Hooks add auth, logging, and middleware to every request',
		whatBreaksIfSkipped: 'No authentication, no request processing',
		projectProof: 'Add cookie-based auth to your blog',
		tags: ['sveltekit', 'hooks', 'middleware']
	},
	{
		slug: 'tailwind-basics',
		title: 'Tailwind CSS Basics',
		description: 'Utility classes, configuration, and common patterns',
		layer: 'framework',
		order: 19,
		prerequisites: ['css-grid'],
		unlocks: ['tailwind-responsive', 'design-systems'],
		estimatedMinutes: 60,
		whyNext: 'Tailwind accelerates styling 3-5x over traditional CSS',
		whatBreaksIfSkipped: 'Slower styling, inconsistent spacing and colors',
		projectProof: 'Restyle your blog entirely with Tailwind utilities',
		tags: ['tailwind', 'css', 'utilities']
	},
	{
		slug: 'tailwind-responsive',
		title: 'Tailwind Responsive',
		description: 'Responsive prefixes, container queries, dark mode',
		layer: 'framework',
		order: 20,
		prerequisites: ['tailwind-basics', 'css-responsive'],
		unlocks: ['design-systems'],
		estimatedMinutes: 45,
		whyNext: 'Responsive Tailwind is how modern apps handle breakpoints',
		whatBreaksIfSkipped: 'Inconsistent mobile experience',
		projectProof: 'Make your blog fully responsive with dark mode toggle',
		tags: ['tailwind', 'responsive', 'dark-mode']
	},
	{
		slug: 'a11y-fundamentals',
		title: 'Accessibility Fundamentals',
		description: 'ARIA, keyboard nav, color contrast, screen readers',
		layer: 'professional',
		order: 21,
		prerequisites: ['html-semantics', 'sveltekit-hooks'],
		unlocks: [],
		estimatedMinutes: 90,
		whyNext: 'Accessible apps reach more users and are legally required',
		whatBreaksIfSkipped: 'Users with disabilities can\'t use your app',
		projectProof: 'Audit and fix accessibility on your blog',
		tags: ['accessibility', 'a11y', 'aria']
	},
	{
		slug: 'perf-optimization',
		title: 'Performance Optimization',
		description: 'Core Web Vitals, lazy loading, code splitting, caching',
		layer: 'professional',
		order: 22,
		prerequisites: ['sveltekit-hooks'],
		unlocks: [],
		estimatedMinutes: 90,
		whyNext: 'Slow apps lose users. Performance is a feature.',
		whatBreaksIfSkipped: 'Slow load times, poor Lighthouse scores',
		projectProof: 'Optimize your blog to score 90+ on all Lighthouse metrics',
		tags: ['performance', 'optimization', 'web-vitals']
	},
	{
		slug: 'testing-basics',
		title: 'Testing Fundamentals',
		description: 'Unit, integration, and E2E testing with Vitest and Playwright',
		layer: 'professional',
		order: 23,
		prerequisites: [],
		unlocks: ['ci-cd'],
		estimatedMinutes: 120,
		whyNext: 'Tests catch bugs before users do',
		whatBreaksIfSkipped: 'Regressions, fear of refactoring, no confidence in deploys',
		projectProof: 'Write tests for your blog\'s critical paths',
		tags: ['testing', 'vitest', 'playwright']
	},
	{
		slug: 'git-workflow',
		title: 'Git Workflow',
		description: 'Branching, commits, PRs, rebasing, and collaboration',
		layer: 'professional',
		order: 24,
		prerequisites: [],
		unlocks: ['ci-cd'],
		estimatedMinutes: 60,
		whyNext: 'Every professional project uses Git',
		whatBreaksIfSkipped: 'Lost work, merge conflicts, chaotic history',
		projectProof: 'Create a feature branch workflow with PR reviews',
		tags: ['git', 'version-control', 'workflow']
	},
	{
		slug: 'ci-cd',
		title: 'CI/CD Pipelines',
		description: 'GitHub Actions, automated testing, deployment pipelines',
		layer: 'professional',
		order: 25,
		prerequisites: ['testing-basics', 'git-workflow'],
		unlocks: [],
		estimatedMinutes: 60,
		whyNext: 'Automation prevents broken deploys',
		whatBreaksIfSkipped: 'Manual deploys, forgotten tests, broken production',
		projectProof: 'Set up GitHub Actions to test and deploy on push',
		tags: ['ci-cd', 'github-actions', 'automation']
	},
	{
		slug: 'seo-basics',
		title: 'SEO Fundamentals',
		description: 'Meta tags, Open Graph, sitemaps, structured data',
		layer: 'professional',
		order: 26,
		prerequisites: [],
		unlocks: [],
		estimatedMinutes: 45,
		whyNext: 'SEO makes your work discoverable',
		whatBreaksIfSkipped: 'Content invisible to search engines',
		projectProof: 'Add meta tags, OG images, and sitemap to your blog',
		tags: ['seo', 'meta', 'marketing']
	},
	{
		slug: 'design-systems',
		title: 'Design Systems',
		description: 'Tokens, component libraries, consistent UI patterns',
		layer: 'professional',
		order: 27,
		prerequisites: ['tailwind-basics'],
		unlocks: [],
		estimatedMinutes: 90,
		whyNext: 'Design systems scale consistency across features',
		whatBreaksIfSkipped: 'Inconsistent UI, duplicated components, visual debt',
		projectProof: 'Build a mini design system with button, input, and card components',
		tags: ['design', 'systems', 'components']
	},
	{
		slug: 'typescript-basics',
		title: 'TypeScript Basics',
		description: 'Types, interfaces, generics, and type safety',
		layer: 'professional',
		order: 28,
		prerequisites: [],
		unlocks: [],
		estimatedMinutes: 120,
		whyNext: 'TypeScript catches bugs at compile time',
		whatBreaksIfSkipped: 'Runtime type errors, worse IDE support',
		projectProof: 'Add TypeScript types to your Svelte project',
		tags: ['typescript', 'types', 'safety']
	}
];
